.TH gloobus-preview-configuration 1 "November 8 2010" "David Green"
.SH NAME
gloobus-preview-configuration \- edit preferences for gloobus-preview.
.PP
.SH SYNOPSIS
.B gloobus-preview-configuration
.PP
.SH DESCRIPTION
This will open a window with configuration options for gloobus-preview.
.PP
.SH AUTHOR
.TP
David Green <david4dev@gmail.com>
