.TH gloobus-preview 1 "November 8 2010" "David Green"
.SH NAME
gloobus-preview \- View a quick preview of a file.
.PP
.SH SYNOPSIS
.B gloobus-preview FILE_PATH
.PP
.SH DESCRIPTION
Gloobus preview will show a preview of the file (or folder) given by the FILE_PATH option.
.PP
.SH AUTHOR
.TP
David Green <david4dev@gmail.com>
